app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
//Route login
Route::get( '/', [ 'middleware' => 'guest', 'as' => 'getLogin', 'uses' => 'Auth\AuthController@getLogin' ] );
Route::post( '/', [ 'middleware' => 'guest', 'as' => 'postLogin', 'uses' => 'Auth\AuthController@postLogin' ] );
//Route logout
Route::get( 'logout', [ 'as' => 'getLogout', 'uses' => 'Auth\AuthController@getLogout'] );
//Route Dashboard
Route::get( 'dashboard', [ 'middleware' => 'auth', 'as' => 'getDashboard', 'uses' => 'DashboardController@get_dashboard' ]);
//Route staff
Route::resource( 'staff', 'StaffController' );
//Route department
Route::resource( 'department', 'DepartmentController' );
//Route review
Route::resource( 'review', 'ReviewController' );
//Route level
Route::resource( 'level', 'LevelController' );
//Route team
Route::resource( 'team', 'TeamController' );
//Route export Excel file
Route::get( 'excel', [ 'as' => 'exportExcel', 'uses' => 'ExportController@export_excel' ] );
//Route delete staff belong a team
Route::get( 'delete/{id}', [ 'middleware' => 'auth', 'as' => 'deleteStaffTeam', 'uses' => 'DeleteController@staff_team_delete' ] );
//Route edit user information 
Route::get( 'profile', [ 'middleware' => 'auth', 'as' => 'getProfile', 'uses' => 'ProfileController@get_profile' ] );
Route::post( 'profile', [ 'middleware' => 'auth', 'as' => 'postProfile', 'uses' => 'ProfileController@post_profile' ] );

app/Http/Controllers/ReviewController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Review;
use App\Staff;
use Auth;
use Gate;

class ReviewController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if ( Gate::denies( 'system_admin' ) )
        {
            $reviewer               =   Auth::user();
            $review                 =   new Review;
            $review->staff_id       =   $request->id;
            $review->reviewer_id    =   $reviewer->id;
            $review->point          =   $request->point;
            $review->comment        =   $request->comment;
            $review->active         =   1;
            $review->save();
            return redirect()->back();
        } else {
            return view('admin.error403');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if ( Gate::denies( 'system_admin' ) )
        {
            $staff      = Staff::find($id);
            $reviewer   = Auth::user();
            $review     = Review::where( 'staff_id', $id )
                                ->where( 'active', 1 )
                                ->get();
            return view('admin.review.add', compact('review', 'staff', 'reviewer'));
        } else {
            return view('admin.error403');
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/review/add.blade.php
@extends('admin.master')
@section('header','Review')
@section('action','Add')
@section('title','Review-Add')
@section('content')
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-7" style="padding-bottom:120px">
                        <form action="{!! route('review.store') !!}" method="POST">
                        <input type="hidden" name="_token" value="{!! csrf_token() !!}">
                            <div class="form-group">
                                <label>Staff ID</label>
                                <input class="form-control" name="id" readonly="true" value="{!! $staff->id !!}" />
                            </div>
                            <div class="form-group">
                                <label>Staff Email</label>
                                <input class="form-control" name="email" readonly="true" value="{!! $staff->email !!}" />
                            </div>
                            <div class="form-group">
                                <label>Staff Name</label>
                                <input class="form-control" name="name" readonly="true" value="{!! $staff->name !!}" />
                            </div>
                            <div class="form-group">
                                <label>Staff Phone</label>
                                <input class="form-control" type="number" min="0" name="phone" readonly="true" value="{!! $staff->phone !!}" />
                            </div>
                            <div class="form-group">
                                <label>Staff Birthday</label>
                                <input class="form-control" type="text" name="birthday" readonly="true" value="{!! $staff->birthday !!}" />
                            </div>
                            <div class="form-group">
                                <label>Reviewer Name</label>
                                <input class="form-control" type="text" min="0" name="reviewer" readonly="true" value="{!! $reviewer->name !!}" />
                            </div>
                            <div class="form-group">
                                <label>Point</label>
                                <input class="form-control" type="range" onchange="updateTextInput(this.value);" min="0" max="10" name="point" placeholder="Please Enter Staff Phone" />
                                <input class="form-control" type="text" readonly="true" id="rangeValue" value="0">
                            </div>
                            <div class="form-group">
                                <label>Reviewer Comment</label>
                                <input class="form-control" type="text" name="comment" value="" />
                            </div>
                            <button type="submit" class="btn btn-default">Review Add</button>
                        </form>
                </div>
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Review List
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="dataTable_wrapper">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr align="center">
                                            <th>Number</th>
                                            <th>Reviewer</th>
                                            <th>Point</th>
                                            <th>Comment</th>
                                            <th>Date</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php $number = 0; ?>
                                        @foreach ( $review as $rv )
                                            <?php $number += 1; ?>
                                            <tr class="even gradeC" align="center">
                                                <td>{!! $number !!}</td>
                                                <td>{!! $rv->reviewer->name !!}</td>
                                                <td>{!! $rv->point !!}</td>
                                                <td>{!! $rv->comment !!}</td>
                                                <td>{!! $rv->created_at !!}</td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
@endsection

resources/views/admin/review/list-staff.blade.php
@extends('admin.master')
@section('header','Staff')
@section('action','List')
@section('title','Staff-List')
@section('content')
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    List Staff Review
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="dataTable_wrapper">
                        <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                            <thead>
                                <tr align="center">
                                    <th>Number</th>
                                    <th>Name</th>
                                    <th>Phone</th>
                                    <th>Birthday</th>
                                    <th>Position</th>
                                    <th>Level</th>
                                    <th>Review</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php $number = 0; ?>
                                @foreach ( $staff as $st )                                   
                                        <tr class="even gradeC" align="center">
                                            <?php $number += 1; ?>
                                            <td>{!! $number !!}</td>
                                            <td>{!! $st->name !!}</td>
                                            <td>{!! $st->phone !!}</td>
                                            <td>{!! $st->birthday !!}</td>
                                            <td>{!! $st->position->name !!}</td>
                                            <td>{!! $st->level->name !!}</td>
                                            <td class="center"><i class="fa fa-pencil fa-fw"></i> <a href="{!! route('review.show',$st->id) !!}">Review</a></td>
                                        </tr>                                   
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection