app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
//Route login
Route::get( '/', [ 'middleware' => 'guest', 'as' => 'getLogin', 'uses' => 'Auth\AuthController@getLogin' ] );
Route::post( '/', [ 'middleware' => 'guest', 'as' => 'postLogin', 'uses' => 'Auth\AuthController@postLogin' ] );
//Route logout
Route::get( 'logout', [ 'as' => 'getLogout', 'uses' => 'Auth\AuthController@getLogout'] );
//Route Dashboard
Route::get( 'dashboard', [ 'middleware' => 'auth', 'as' => 'getDashboard', 'uses' => 'DashboardController@get_dashboard' ]);
//Route staff
Route::resource( 'staff', 'StaffController' );
//Route department
Route::resource( 'department', 'DepartmentController' );
//Route review
Route::resource( 'review', 'ReviewController' );
//Route level
Route::resource( 'level', 'LevelController' );
//Route team
Route::resource( 'team', 'TeamController' );
//Route export Excel file
Route::get( 'excel', [ 'as' => 'exportExcel', 'uses' => 'ExportController@export_excel' ] );
//Route delete staff belong a team
Route::get( 'delete/{id}', [ 'middleware' => 'auth', 'as' => 'deleteStaffTeam', 'uses' => 'DeleteController@staff_team_delete' ] );
//Route edit user information 
Route::get( 'profile', [ 'middleware' => 'auth', 'as' => 'getProfile', 'uses' => 'ProfileController@get_profile' ] );
Route::post( 'profile', [ 'middleware' => 'auth', 'as' => 'postProfile', 'uses' => 'ProfileController@post_profile' ] );

app/Department.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Department extends Model
{
    protected 	$table 		=	'department';
    protected 	$fillable	=	[ 'name', 'active' ];
    public 		$timestamps	=	false;
}

app/Http/Controllers/DepartmentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Department;
use App\Http\Requests\AddDepartmentRequest;
use Gate;

class DepartmentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index()
    {
        if ( Gate::allows( 'system_admin' ) )
        {
            $department = Department::where( 'active', 1 )
                                    ->where( 'id', '!=', 6 )
                                    ->get();
            return view('admin.department.list', compact( 'department' ));
        } else {
            return view('admin.error403');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if ( Gate::allows( 'system_admin' ) )
        {
            return view('admin.department.add');
        } else {
            return view('admin.error403');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AddDepartmentRequest $request)
    {
        if ( Gate::allows( 'system_admin' ) )
        {
            $department         = new Department;
            $department->name   = $request->name;
            $department->active = $request->active;
            $department->save();
            return redirect()->route('department.index'); 
        } else {
            return view('admin.error403');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if ( Gate::allows( 'system_admin' ) )
        {
            $department = Department::find($id);
            return view('admin.department.edit', compact('department'));
        } else {
            return view('admin.error403');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(AddDepartmentRequest $request, $id)
    {
        if ( Gate::allows( 'system_admin' ) )
        {
            $department         = Department::find($id);
            $department->name   = $request->name;
            $department->active = $request->active;
            $department->save();
            return redirect()->route('department.index'); 
        } else {
            return view('admin.error403');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if ( Gate::allows( 'system_admin' ) )
        {
            $department = Department::findOrFail($id);
            $department->delete();
            return redirect()->route('department.index');
        } else {
            return view('admin.error403');
        }
    }
}

resources/views/admin/department/add.blade.php
@extends('admin.master')
@section('header','Department')
@section('action','Add')
@section('title','Department-Add')
@section('content') 
    <!-- /.col-lg-12 -->
    
    <div class="col-lg-7" style="padding-bottom:120px">
        <form action="{!! route('department.store') !!}" method="POST">
        <input type="hidden" name="_token" value="{!! csrf_token() !!}">
            <div class="form-group">
                <label>Department Name</label>
                <input class="form-control" name="name" value="{!!old('name')!!}" placeholder="Please Enter Department Name" />
                <div class="error">{!! $errors->first('name') !!}</div>
            </div>
            <div class="form-group">
                <label>Department Active</label>
                <label class="radio-inline">
                    <input name="active" value="0" checked="" type="radio">Deactive
                </label>
                <label class="radio-inline">
                    <input name="active" value="1" type="radio">Active
                </label>
            </div>
            <button type="submit" class="btn btn-default">Department Add</button>
            <button type="reset" class="btn btn-default">Reset</button>
        </form>
    </div>
@endsection

resources/views/admin/department/edit.blade.php
@extends('admin.master')
@section('header','Department')
@section('action','Edit')
@section('title','Department-Edit')
@section('content') 
    <!-- /.col-lg-12 -->
    
    <div class="col-lg-7" style="padding-bottom:120px">
    {!! Form::open(array('route'=>array('department.update',$department->id),'method'=>'PUT')) !!}
        <form action="" method="">
        <input type="hidden" name="_token" value="{!! csrf_token() !!}">
            <div class="form-group">
                <label>Department Name</label>
                <input class="form-control" name="name" value="{!! $department->name !!}" placeholder="Please Enter Category Name" />
                <div class="error">{!! $errors->first('name') !!}</div>
            </div>
            <div class="form-group">
                <?php $check = 'true'; ?>
                <label>Department Active</label>
                @if ( $department->active == 0 )               
                <label class="radio-inline">
                    <input name="active" value="0" checked="<?php echo $check ?>" type="radio">Deactive
                </label>
                <label class="radio-inline">
                    <input name="active" value="1" checked="" type="radio">Active
                </label>
                @elseif ( $department->active == 1 )
                <label class="radio-inline">
                    <input name="active" value="0" checked="" type="radio">Deactive
                </label>
                <label class="radio-inline">
                    <input name="active" value="1" checked="<?php echo $check ?>" type="radio">Active
                </label>
                @endif
            </div>
            <button type="submit" class="btn btn-default">Department Edit</button>
            <button type="reset" class="btn btn-default">Reset</button>
        </form>
    {!! Form::close() !!}
    </div>
@endsection

resources/views/admin/department/list.blade.php
@extends('admin.master')
@section('header','Department')
@section('action','List')
@section('title','Department-List')
@section('content')
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Department List
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="dataTable_wrapper">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr align="center">
                                            <th>Number</th>
                                            <th>Name</th>
                                            <th>Delete</th>
                                            <th>Edit</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php $number = 0; ?>
                                        @foreach ( $department as $dep )
                                            <?php $number += 1; ?>
                                            <tr class="even gradeC" align="center">
                                                <td>{!! $number !!}</td>
                                                <td>{!! $dep->name !!}</td>
                                                {!! Form::open(array('route'=>array('department.destroy',$dep->id),'method'=>'DELETE')) !!}
                                                    <form action="" method="">
                                                        <td class="center"><i class="fa fa-trash-o  fa-fw"></i><button onclick="return Confirm('Are you want to delete this department!')" type="submit" id="delete" class="btn btn-link">Delete</button></td>
                                                    </form>
                                                {!! Form::close() !!}               
                                                <td class="center"><i class="fa fa-pencil fa-fw"></i> <a href="{!! route('department.edit',$dep->id) !!}">Edit</a></td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
@endsection