app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
//Route login
Route::get( '/', [ 'middleware' => 'guest', 'as' => 'getLogin', 'uses' => 'Auth\AuthController@getLogin' ] );
Route::post( '/', [ 'middleware' => 'guest', 'as' => 'postLogin', 'uses' => 'Auth\AuthController@postLogin' ] );
//Route logout
Route::get( 'logout', [ 'as' => 'getLogout', 'uses' => 'Auth\AuthController@getLogout'] );
//Route Dashboard
Route::get( 'dashboard', [ 'middleware' => 'auth', 'as' => 'getDashboard', 'uses' => 'DashboardController@get_dashboard' ]);
//Route staff
Route::resource( 'staff', 'StaffController' );
//Route department
Route::resource( 'department', 'DepartmentController' );
//Route review
Route::resource( 'review', 'ReviewController' );
//Route level
Route::resource( 'level', 'LevelController' );
//Route team
Route::resource( 'team', 'TeamController' );
//Route export Excel file
Route::get( 'excel', [ 'as' => 'exportExcel', 'uses' => 'ExportController@export_excel' ] );
//Route delete staff belong a team
Route::get( 'delete/{id}', [ 'middleware' => 'auth', 'as' => 'deleteStaffTeam', 'uses' => 'DeleteController@staff_team_delete' ] );
//Route edit user information 
Route::get( 'profile', [ 'middleware' => 'auth', 'as' => 'getProfile', 'uses' => 'ProfileController@get_profile' ] );
Route::post( 'profile', [ 'middleware' => 'auth', 'as' => 'postProfile', 'uses' => 'ProfileController@post_profile' ] );

app/Staff.php
<?php
namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class Staff extends Model implements AuthenticatableContract,
                                    AuthorizableContract,
                                    CanResetPasswordContract
{
    use Authenticatable, Authorizable, CanResetPassword;
    protected 	$table 		=	'staff';
    protected   $hidden     =   ['password', 'remember_token'];
    protected 	$fillable 	=	[ 'email', 'password', 'name', 'phone', 'birthday', 'position_id', 'level_id', 'department_id', 'active' ];
    public 		$timestamps =	false;

    public function level()
    {
    	return $this->belongsTo( 'App\Level', 'level_id' );
    }
    public function department()
    {
    	return $this->belongsTo( 'App\Department', 'department_id' );
    }
    public function position()
    {
    	return $this->belongsTo( 'App\Position', 'position_id' );
    }
    public function review()
    {
    	return $this->hasMany( 'App\Review', 'staff_id' );
    }
}

app/Http/Controllers/StaffController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Staff;
use App\Http\Requests\AddStaffRequest;
use App\Http\Requests\UpdateStaffRequest;
use App\Department;
use App\Level;
use App\Position;
use Hash;
use Gate;
use Auth;
use App\StaffTeam;

class StaffController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index()
    {
        if ( Gate::denies( 'system_admin' ) )
        {
            if ( Gate::allows( 'manager' ) )
            {
                $staff = Staff::where( 'active', 1 )
                                ->whereNotIn( 'level_id', Level::select( 'id' )->where( 'role_id', 1 )->orWhere( 'role_id', 2 )->get() )
                                ->get();
            }
            if ( Gate::allows( 'team_leader' ) )
            {
                $staff = Staff::where( 'active', 1 )
                                ->where( 'department_id', Auth::user()->department_id )
                                ->whereIn( 'level_id', Level::select( 'id' )->where( 'role_id', 4 )->get() )
                                ->get();
            }
            if ( Gate::allows( 'developer' ) )
            {
                return view( 'admin.error403' );
            }
            return view( 'admin.staff.list', compact( 'staff' ) );
        } else {
            return view( 'admin.error403' );
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if( Gate::denies( 'developer' ) )
        {
            $department =   Department::where( 'active', 1 )->get();
            if ( Gate::allows( 'system_admin' ) )
            {
                $level      =   Level::where( 'role_id', 2 )
                                        ->orWhere( 'role_id', 3 )
                                        ->where( 'active', 1 )
                                        ->get();
                $position   =   Position::where( 'id', 3 )->where( 'active', 1 )->get();
            }
            if ( Gate::allows( 'manager' ) )
            {
                $level      =   Level::where( 'role_id', 3 )
                                        ->orWhere( 'role_id', 4 )
                                        ->where( 'active', 1 )
                                        ->get();
                $position   =   Position::where( 'active', 1 )->get();
            }
            if ( Gate::allows( 'team_leader' ) )
            {
                $level      =   Level::where( 'role_id', 4 )->where( 'active', 1 )->get();
                $position   =   Position::where( 'active', 1 )->get();
                $department =   Department::where( 'active', 1 )
                                            ->where( 'id', Auth::user()->department_id )
                                            ->get();
            }
            return view( 'admin.staff.add', compact( 'level', 'position', 'department' ) );
        } else {
            return view('admin.error403');
        }

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AddStaffRequest $request)
    {
        $staff                  = new Staff;
        $staff->email           = $request->email;
        $staff->password        = Hash::make($request->password);
        $staff->name            = $request->name;
        $staff->phone           = $request->phone;
        $staff->birthday        = $request->birthday;
        $staff->position_id     = $request->position;
        $staff->level_id        = $request->level;
        $staff->department_id   = $request->department;
        $staff->active          = $request->active;
        $level                  = Level::select( 'role_id' )->find($request->level);
        $staff_level            = $level->role_id;
        if( Gate::allows( 'role_create', $staff_level ) ) {
            $staff->save();
            return redirect()->route('staff.index');
        } else {
            return view('admin.error403');
        }
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if ( Gate::denies( 'system_admin' ) )
        {
            $staff = Staff::where('department_id', $id)
                            ->where( 'id', '!=', Auth::user()->id )
                            ->get();
            if ( Gate::allows( 'developer' ) )
            {
                $staff_team = Staff::whereIn( 'id', StaffTeam::select( 'staff_id' )->whereIn( 'team_id', StaffTeam::select( 'team_id' )->where( 'staff_id', Auth::user()->id )->get() )
                                    ->get() );
                $staff      = Staff::where('department_id', $id)
                                    ->where( 'id', '!=', Auth::user()->id )
                                    ->whereIn( 'level_id', Level::select( 'id' )->where( 'role_id', '!=', 3 )->get() )
                                    ->union($staff_team)
                                    ->get();
            }
            return view('admin.review.list-staff', compact('staff'));
        } else {
            return view('admin.error403');
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if ( Gate::denies( 'system_admin' ) )
        {            
            $department = Department::where( 'active', 1 )->get();
            $position   = Position::where( 'active', 1 )->get();
            $staff      = Staff::find($id);
            if ( Gate::allows( 'team_leader' ) )
            {
                $position   = Position::where( 'active', 1 )
                                        ->where( 'id', '!=', 3 )
                                        ->get();
                $department = Department::where( 'active', 1 )
                                        ->where( 'id', Auth::user()->department_id )
                                        ->get();
                $level      =   Level::where( 'role_id', 4 )->where( 'active', 1 )->get();
            }
            if ( Gate::allows( 'manager' ) )
            {
                $level      =   Level::where( 'role_id', 3 )
                                        ->orWhere( 'role_id', 4 )
                                        ->where( 'active', 1 )
                                        ->get();
                $position   =   Position::where( 'active', 1 )->get();
            }
            if ( Gate::allows( 'developer' ) )
            {
                return view('admin.error403');
            }
            return view('admin.staff.edit', compact( 'staff', 'level', 'department', 'position' ));
        } else {
            return view('admin.error403');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateStaffRequest $request, $id)
    {
        if ( Gate::denies( 'system_admin' ) )
        {
            $staff                  = Staff::find($id);
            $staff->email           = $request->email;
            $staff->name            = $request->name;
            $staff->phone           = $request->phone;
            $staff->birthday        = $request->birthday;
            $staff->position_id     = $request->position;
            $staff->level_id        = $request->level;
            $staff->department_id   = $request->department;
            $staff->active          = $request->active;
            $staff->save();
            return redirect()->route('staff.index');
        } else {
            return view('admin.error403');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if ( Gate::denies( 'system_admin' ) )
        {
            $staff = Staff::findOrFail($id);
            $staff->delete();
            return redirect()->route('staff.index');
        } else {
            return view('admin.error403');
        }
    }
}

resources/views/admin/staff/add.blade.php
@extends('admin.master')
@section('header','Staff')
@section('action','Add')
@section('title','Staff-Add')
@section('content') 
    <!-- /.col-lg-12 -->
    
    <div class="col-lg-7" style="padding-bottom:120px">
        <form action="{!! route('staff.store') !!}" method="POST">
        <input type="hidden" name="_token" value="{!! csrf_token() !!}">
            <div class="form-group">
                <label>Department</label>
                <select name="department" class="form-control"> 
                    @foreach ( $department as $deps )
                        <option value="{!! $deps->id !!}">{!! $deps->name !!}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                <label>Position</label>
                <select name="position" class="form-control">
                    @foreach ( $position as $pos )
                        <option value="{!! $pos->id !!}">{!! $pos->name !!}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                <label>Level</label>
                <select name="level" class="form-control">
                    @foreach ( $level as $lev )
                        <option value="{!! $lev->id !!}">{!! $lev->name !!}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                <label>Staff Email</label>
                <input class="form-control" name="email" value="{!!old('email')!!}" placeholder="Please Enter Staff Email" />
                <div class="error">{!! $errors->first('email') !!}</div>
            </div>
            <div class="form-group">
                <label>Staff Password</label>
                <input class="form-control" type="password" name="password" value="{!!old('password')!!}" placeholder="Please Enter Staff Password" />
                <div class="error">{!! $errors->first('password') !!}</div>
            </div>
            <div class="form-group">
                <label>Staff Name</label>
                <input class="form-control" name="name" value="{!!old('name')!!}" placeholder="Please Enter Staff Name" />
                <div class="error">{!! $errors->first('name') !!}</div>
            </div>
            <div class="form-group">
                <label>Staff Phone</label>
                <input class="form-control" type="number" min="0" name="phone" value="{!!old('phone')!!}" placeholder="Please Enter Staff Phone" />
                <div class="error">{!! $errors->first('phone') !!}</div>
            </div>
            <div class="form-group">
                <label>Staff Birthday</label>
                <input class="form-control" type="text" id="datepicker" name="birthday" value="{!!old('birthday')!!}" placeholder="Please Choose Staff Birthday" />
                <div class="error">{!! $errors->first('birthday') !!}</div>
            </div>
            <div class="form-group">
                <label>Staff Active</label>
                <label class="radio-inline">
                    <input name="active" value="0" checked="" type="radio">Deactive
                </label>
                <label class="radio-inline">
                    <input name="active" value="1" type="radio">Active
                </label>
            </div>
            <button type="submit" class="btn btn-default">Staff Add</button>
            <button type="reset" class="btn btn-default">Reset</button>
        </form>
    </div>
@endsection

resources/views/admin/staff/edit.blade.php
@extends('admin.master')
@section('header','Staff')
@section('action','Edit')
@section('title','Staff-Edit')
@section('content') 
    <!-- /.col-lg-12 -->
    
    <div class="col-lg-7" style="padding-bottom:120px">
        {!! Form::open(array('route'=>array('staff.update',$staff->id),'method'=>'PUT')) !!}
            <div class="form-group">
                <label>Department</label>
                <select name="department" class="form-control">
                    <option value="{!! $staff->department->id !!}">{!! $staff->department->name !!}</option>
                    @foreach ( $department as $deps )
                        <option value="{!! $deps->id !!}">{!! $deps->name !!}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                <label>Position</label>
                <select name="position" class="form-control">
                    <option value="{!! $staff->position->id !!}">{!! $staff->position->name !!}</option>
                    @foreach ( $position as $pos )
                        <option value="{!! $pos->id !!}">{!! $pos->name !!}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                <label>Level</label>
                <select name="level" class="form-control">
                    <option value="{!! $staff->level->id !!}">{!! $staff->level->name !!}</option>
                    @foreach ( $level as $lev )
                        <option value="{!! $lev->id !!}">{!! $lev->name !!}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                <label>Staff Email</label>
                <input class="form-control" name="email" value="{!! $staff->email !!}" readonly="true" />
                <div class="error">{!! $errors->first('email') !!}</div>
            </div>
            <div class="form-group">
                <label>Staff Name</label>
                <input class="form-control" name="name" value="{!! $staff->name !!}" placeholder="Please Enter Category Name" />
                <div class="error">{!! $errors->first('name') !!}</div>
            </div>
            <div class="form-group">
                <label>Staff Phone</label>
                <input class="form-control" type="number" min="0" name="phone" value="{!! $staff->phone !!}" placeholder="Please Enter Category Order" />
                <div class="error">{!! $errors->first('phone') !!}</div>
            </div>
            <div class="form-group">
                <label>Staff Birthday</label>
                <input class="form-control" type="text" id="datepicker" name="birthday" value="{!! $staff->birthday !!}" placeholder="Please Enter Category Keywords" />
                <div class="error">{!! $errors->first('birthday') !!}</div>
            </div>
            <div class="form-group">
            	<?php $check = 'true'; ?>
            	<label>Staff Active</label>
            	@if ( $staff->active == 0 )               
                <label class="radio-inline">
                    <input name="active" value="0" checked="<?php echo $check ?>" type="radio">Deactive
                </label>
                <label class="radio-inline">
                    <input name="active" value="1" checked="" type="radio">Active
                </label>
                @elseif ( $staff->active == 1 )
                <label class="radio-inline">
                    <input name="active" value="0" checked="" type="radio">Deactive
                </label>
                <label class="radio-inline">
                    <input name="active" value="1" checked="<?php echo $check ?>" type="radio">Active
                </label>
                @endif
            </div>
            <button type="submit" class="btn btn-default">Staff Edit</button>
            <button type="reset" class="btn btn-default">Reset</button>
        {!! Form::close() !!}
    </div>
@endsection

resources/views/admin/staff/list.blade.php
@extends('admin.master')
@section('header','Staff')
@section('action','List')
@section('title','Staff-List')
@section('content')
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Staff List
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="dataTable_wrapper">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr align="center">
                                            <th>Number</th>
                                            <th>Name</th>
                                            <th>Phone</th>
                                            <th>Birthday</th>
                                            <th>Position</th>
                                            <th>Department</th>
                                            <th>Level</th>
                                            <th>Delete</th>
                                            <th>Edit</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php $number = 0; ?>
                                        @foreach ( $staff as $st )
                                            <tr class="even gradeC" align="center">
                                                <?php $number += 1; ?>
                                                <td>{!! $number !!}</td>
                                                <td>{!! $st->name !!}</td>
                                                <td>{!! $st->phone !!}</td>
                                                <td>{!! $st->birthday !!}</td>
                                                <td>{!! $st->position->name !!}</td>
                                                <td>{!! $st->department->name!!}</td>
                                                <td>{!! $st->level->name !!}</td>
                                                {!! Form::open(array('route'=>array('staff.destroy',$st->id),'method'=>'DELETE')) !!}
                                                    <form action="" method="">
                                                        <td class="center"><i class="fa fa-trash-o  fa-fw"></i><button onclick="return Confirm('Are you want to delete this staff!')" type="submit" id="delete" class="btn btn-link">Delete</button></td>
                                                    </form>
                                                {!! Form::close() !!}               
                                                <td class="center"><i class="fa fa-pencil fa-fw"></i> <a href="{!! route('staff.edit',$st->id) !!}">Edit</a></td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
@endsection